---
- hosts: local
  become_method: sudo

  roles:
    - role: geerlingguy.docker
      tags: ["setup"]
      become: true
      docker_service_state: started
      docker_service_enabled: true
      docker_restart_handler_state: restarted
      docker_install_compose: true

    - role: ocha.dotnet-core
      dotnet_package: "dotnet-sdk-2.2"
      become: true

  tasks:
    - name: Install common
      include_tasks: tasks/install_common.yml

    - name: Setup bash 
      include_tasks: tasks/bash.yml

    - name: Setup ssh
      include_tasks: tasks/ssh.yml

    - name: Install python
      include_tasks: tasks/python.yml

    - name: Install Vim
      include_tasks: tasks/vim.yml



