---
- name: Remove firefox
  apt:
    name: firefox
    state: absent
  become: true

- name: Install common packages
  apt:
    name:
      - git
      - chromium-browser
  become: true

- name: Set git email
  command: git config --global user.email "hpeters1024.nl"

- name: Set git username 
  command: git config --global user.name "Hugo"
