---
- name: Remove firefox
  apt:
    name: firefox
    state: absent
  become: true

- name: Install common packages
  apt:
    name:
      - git
      - chromium-browser
      - dos2unix
  become: true

- name: Set git email
  command: git config --global user.email "hpeters1024.nl"

- name: Set git username 
  command: git config --global user.name "Hugo"

- name: Create docker group
  command: groupadd docker
  become: true
  ignore_errors: yes

- name: Add user to the docker group
  command: usermod -aG docker hugo
  become: true
