---
- name: Add deadsnakes repo
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
    update_cache: yes
  become: true

- name: Install python3
  apt:
    name: "{{item}}"
  become: true
  with_items:
    - python3.7
    - python3-pip
    - python3-tk

- name: Install pipenv
  pip:
    name: pipenv
    state: latest
  become: true

- name: Update all packages
  apt:
    upgrade: "yes"
    update_cache: true
    cache_valid_time: 3600
  become: true

